version: "3.8"

services:
  backend:
    image: magdalenaabinus/todolist-backend:latest
    restart: always
    environment:
    CONNECTION_URL: mongodb+srv://admin:admin@cluster0.hei0goq.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    PORT: 5000
    REFRESH_TOKEN_SECRET: duarduar87775530966

    EMAIL_USER: magdalena.aretha@gmail.com
    EMAIL_PASSWORD: iwwu sbhq jklx sscn

    ports:
      - "3077:3077"

  frontend:
    image: magdalenaabinus/todolist-frontend:latest
    restart: always
    depends_on:
      - backend
    ports:
      - "3078:3078"