name: Todolist CI/CD

on:
  push:
    branches:
      - master
    paths-ignore:
      - "README.md"
  pull_request:
    branches:
      - master

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{ magdalenaabinus }} -p ${{ $ummeR160505 }}

      - name: Build and Push Backend Image
        run: |
          docker build -t ${{ magdalenaabinus }}/todolist-backend:latest ./server
          docker push ${{ magdalenaabinus }}/todolist-backend:latest

      - name: Build and Push Frontend Image
        run: |
          docker build -t ${{ magdalenaabinus }}/todolist-frontend:latest ./client
          docker push ${{ magdalenaabinus }}/todolist-frontend:latest

  continuous-deployment:
    needs: continuous-integration
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Docker Rootless Environment
        run: |
          echo "Setting up Docker rootless env..."
          echo "export PATH=$HOME/bin:$PATH" >> $GITHUB_ENV
          echo "export DOCKER_HOST=unix://$XDG_RUNTIME_DIR/docker.sock" >> $GITHUB_ENV

      - name: Pull Latest Backend Image
        run: docker pull ${{ magdalenaabinus }}/todolist-backend:latest

      - name: Pull Latest Frontend Image
        run: docker pull ${{ magdalenaabinus }}/todolist-frontend:latest

      - name: Stop and Remove Old Containers
        run: |
          docker compose down || true
          docker system prune -f

      - name: Run New Containers
        run: |
          docker compose up -d
        env:
    CONNECTION_URL: mongodb+srv://admin:admin@cluster0.hei0goq.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    PORT: 5000
    REFRESH_TOKEN_SECRET: duarduar87775530966

    EMAIL_USER: magdalena.aretha@gmail.com
    EMAIL_PASSWORD: iwwu sbhq jklx sscn